// <auto-generated />
using System;
using IkostProjeMVC.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkostProjeMVC.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IkostProjeMVC.Models.Entities.Bayiler", b =>
                {
                    b.Property<int>("BayiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BayiID"), 1L, 1);

                    b.Property<string>("BayiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HakedisYuzde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BayiID");

                    b.ToTable("Bayilers", (string)null);
                });

            modelBuilder.Entity("IkostProjeMVC.Models.Entities.Siparisler", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"), 1L, 1);

                    b.Property<string>("BayiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BayiID")
                        .HasColumnType("int");

                    b.Property<decimal>("HakedisTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SiparisTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("SiparisID");

                    b.HasIndex("BayiID");

                    b.ToTable("Siparislers", (string)null);
                });

            modelBuilder.Entity("IkostProjeMVC.Models.Entities.Siparisler", b =>
                {
                    b.HasOne("IkostProjeMVC.Models.Entities.Bayiler", "Bayi")
                        .WithMany("Siparislers")
                        .HasForeignKey("BayiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bayi");
                });

            modelBuilder.Entity("IkostProjeMVC.Models.Entities.Bayiler", b =>
                {
                    b.Navigation("Siparislers");
                });
#pragma warning restore 612, 618
        }
    }
}
